name: Deploy to ICDSoft via FTP

on:
  push:
    branches:
      - main  # Or 'master' if that’s your branch name

jobs:
  ftp-deploy:
    name: 📤 Upload website to ICDSoft
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/kourous/www/nikos/
          exclude: |
            **/.git*
            **/.github/**
            **/README.md
            **/*.psd
